---

---

::: {.columns}
:::: {.column width="50%"}
### Executive Committee

**President:** Antonio Lijoi  
**Past President:** Michele Guindani  
**President Elect:** Judith Rousseau  
**Treasurer:** Yanxun Xu  
**Executive Secretary:** Xinyi Xu  
::::

:::: {.column width="50%"}
### Program Council

**Chair:** Yang Ni  
**Vice Chair:** David Frazier  
**Past Chair:** Sameer K. Deshpande
::::

:::: {.column width="100%"}
### Social Media Team

Andrew Brown, Julyan Arbel, Clara Grazian, Collin Cademartori

### Board Members

**2026–2028:**  
Alejandra Avalos Pacheco, David Dahl, Beatrice Franzolini, Stéphanie van der Pas

**2025–2027:**  
Sinead Williamson, Clara Grazian, Sally Paganin, David Rossell

**2024–2026:**  
Antonio Canale, Daniele Durante, Lucia Paci, Georgia Papadogeorgou  
::::
:::

---

---

### Editorial Board

::: {.columns}
:::: {.column width="50%"}
#### Editor  
*Francesco Denti*  [<i class="bi bi-envelope bi-1x"></i>](mailto:francesco.denti@unipd.it)  
::::

:::: {.column width="50%"}

#### Associate Editors  
**Features**  
*Anton Westveld* [<i class="bi bi-envelope bi-1x"></i>](mailto:anton.westveld@anu.edu.au)  
**News of the World**  
*Déborah Sulem* [<i class="bi bi-envelope bi-1x"></i>](mailto:deborah.sulem@bse.eu)  
**Teaching Bayes**  
*Federica Zoe Ricci* [<i class="bi bi-envelope bi-1x"></i>](mailto:fzricci@uci.edu)  

::::

:::



