title: "The ISBA Bulletin"
subtitle: "March 2025 - Vol. 32 No. 1"
css: styles.css
project:
  type: website
  output-dir: docs
format: 
  html:
    number-sections: false
    mainfont: roboto
    fontsize: "20px"
    grid:
      sidebar-width: 300px
      body-width: 1300px
      margin-width: 200px
      gutter-width: 1.5rem
#    grid:
#      sidebar-width: 10px
    toc: true
    toc-depth: 1
    toc-location: left
    toc-title: "In this issue"
    other-links:
      - text: PDF version
        href: Bulletin_noAwards.pdf
      - text: Previous PDF bulletin (before 2025)
        href: https://bayesian.org/resources/bulletin/
        # https://bayesian.org/bulletin/
    page-layout: full
    embed-resources: true
    self-contained-math: true
    toc-expand: true
editor: source
execute:
  freeze: auto
title-block-banner: "#2c4878"